[package]
name = "qttypes"
version = "0.1.4"
edition = "2018"
authors = ["Olivier Goffart <ogoffart@woboq.com>"]
build = "build.rs"
description = "Manually maintained building for Qt basic types"
readme = "README.md"
license = "MIT"
keywords = ["Qt"]
repository = "https://github.com/woboq/qmetaobject-rs"

[dependencies]
cpp = "0.5.6"
chrono = { version = "0.4", optional = true }

[build-dependencies]
cpp_build = "0.5.6"
semver = "0.11"

[package.metadata.docs.rs]
dependencies = [ "qtbase5-dev", "qtdeclarative5-dev" ]
rustc-args = [ "--cfg feature=\"docs-only\"" ]
